### ISSUE TITLE
Memory error for big log file

### ISSUE THREAD

**Issue by maarten00** [rap2hpoutre/laravel-log-viewer#10]
I have a very big (2,5GB) log file in my Laravel application because it used a single log file in the past. I've installed the package, but I'm getting a memory exhausted error. 
[2015-03-23 09:08:50] live.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Allowed memory size of 134217728 bytes exhausted (tried to allocate 2658702094 bytes)'

**Comment by rap2hpoutre** [comment]
2.5GB ;) !! Ok I will try to optimize this. You can try to split your file

**Comment by maarten00** [comment]
To be fair, I'm not expecting that it will be able to render the whole thing, let alone search it. Maybe it should have a (configurable) max amount of lines it will parse.

**Comment by rap2hpoutre** [comment]
I will keep optimization in mind. Thanks you
