### ISSUE TITLE
Charts and more info

### ISSUE THREAD

**Issue by marabesi** [rap2hpoutre/laravel-log-viewer#101]
I was wondering if there is something on the roadmap to implement new ways to see the logs such as charts and different kinds to visualize the log data.

Here go a few suggestions that I was thinking of:

- a pizza chart, based on the log type (error, info, debug)
- a spike graph based on the date

What do you guys think?

**Comment by rap2hpoutre** [comment]
Hi! Thank you for contributing! _(and sorry for late answer)_

There is no plan to add charts in this lib. The purpose of this package is to be really lightweight and to stay easy to install, easy to configure, easy to use (and to be fair, I still don't understand the value of a chart showing error percent by type, but it's just my opinion, I don't judge anyone, and I don't know the needs of others).

Still, [ARKANEDEV](https://github.com/ARCANEDEV) has created [a better Log Viewer](https://github.com/ARCANEDEV/LogViewer) than mine with charts and so on! It should contain everything you want! Feel free to use it if it better fits your need!

**Comment by marabesi** [comment]
Fair enough, thank you!
