### ISSUE TITLE
when i'm executing composer remove rap2hpoutre/laravel-log-viewer i get this error

### ISSUE THREAD

**Issue by Edison6351** [rap2hpoutre/laravel-log-viewer#104]
[Symfony\Component\Debug\Exception\FatalThrowableError]   Class 'Rap2hpoutre\LaravelLogViewer\LaravelLogViewerServiceProvider' not found

**Comment by rap2hpoutre** [comment]
You have to remove this line from `conf/app.php`:

```
Rap2hpoutre\LaravelLogViewer\LaravelLogViewerServiceProvider::class,
```

**Comment by Edison6351** [comment]
ok resolved it thanks for reply and i think you can trying to merge my pr :)
