### ISSUE TITLE
 Problem of displaying logs

### ISSUE THREAD

**Issue by colorkeks** [rap2hpoutre/laravel-log-viewer#107]
Real Expamle: i have supervisor.log with 38000+ rows and size 6,4МB, when i'm try display that file, i get an error "Allowed memory size of *** bytes exhausted (tried to allocate *** bytes)".
Increase the amount of memory in php.ini, is not an option.

Maybe add try catch in LaravelLogViewer(line 133-154), or ignore some logs ? 

Sorry for bad english :)

**Comment by rap2hpoutre** [comment]
Maybe the best option is to split/rotate your logs.
