### ISSUE TITLE
Event Listener 

### ISSUE THREAD

**Issue by rainbowhat** [rap2hpoutre/laravel-log-viewer#110]
Is there anyway i could easily listen to all new logs as i would like it to notify on telegram.

**Comment by ricardocino** [comment]
To be honest I don't think this package is made for something like that. I suggest you take a look at [Sentry](https://sentry.io/welcome/)

**Comment by rap2hpoutre** [comment]
Oops, sorry, late answer.

@ricardocino is right. 

@rainbowhat This package is just a _small tool_ to help starter projects. Consider using something like bugsnag, sentry or even new relic if you want to get notified in telegram. Anyway, self-promotion about a small package I made for Slack with some more informations (not sure it will help you though): https://github.com/rap2hpoutre/laravel-epilog it can help you if you want to build your own package.

I close this issue, let me know if I misunderstood something.
