### ISSUE TITLE
How Export the LogViewerController.php for make my own custom

### ISSUE THREAD

**Issue by fabpin** [rap2hpoutre/laravel-log-viewer#112]
Already have problem with LogViewer, i cant copy the controller from the vendor/rap2hpoutre/laravel-log-viewer/src/controllers/LogViewerController.php to the App/Http/Controllers/LogViewerController.php, appear than the class doesnt exists, if i create, the controller and put the following route parameter, "Route::get('/logs', 'LogViewerController@index');" appear the following error: "Class 'App\Http\Controllers\LaravelLogViewer' not found", i suppose than need instance the vendor/rap2hpoutre/laravel-log-viewer/src/Rap2hpoutre/LaravelLogViewer.php, so already instance the provider on my class, with the namespace "namespace Rap2hpoutre\LaravelLogViewer;" appear "Class 'Rap2hpoutre\LaravelLogViewer\Controller' not found" again, pls any help ? , thanks in advance.

**Comment by rap2hpoutre** [comment]
Oops, sorry to late answer! Did you find any solution for your problem? If not, could you format your issue for better understanding?

**Comment by cino** [comment]
Looks like you're not using the right class name, you should use it like this:

`
Route::get('logs', '\Rap2hpoutre\LaravelLogViewer\LogViewerController@index')
`

( See the difference from your error, it says **LogViewerController** and not just **Controller**
