### ISSUE TITLE
Layout issue when displaying long log file names

### ISSUE THREAD

**Issue by alanwillms** [rap2hpoutre/laravel-log-viewer#114]
Long log file names such as `industries.myapp.cancellations.hybridtest-29-04-2017-12-05.log` explode their containers.

**Comment by rap2hpoutre** [comment]
Thank you for contributing! 

You are right, but I don't know what to do. What do you suggest?

**Comment by alanwillms** [comment]
Sorry, I was in a bit of a hurry at that time but now I was able to fix it. Please review my pull request.

**Comment by rap2hpoutre** [comment]
Thank you!
