### ISSUE TITLE
How to generate different log levels in Lumen

### ISSUE THREAD

**Issue by bharatvaggu** [rap2hpoutre/laravel-log-viewer#117]
How to generate different log levels(Error, Info, Warning etc) using monolog in lumen. Lumen generates only "Error" log level.

**Comment by jeremykenedy** [comment]
Maybe this will help:
Lumens app.php
https://github.com/laravel/lumen/blob/master/bootstrap/app.php

My modified Laravel app to separate the logs:
https://github.com/jeremykenedy/laravel-auth/blob/master/bootstrap/app.php

Laravels app.php
https://github.com/laravel/laravel/blob/master/bootstrap/app.php

**Comment by rap2hpoutre** [comment]
Thank for your contribution. Since it's not a problem about the log viewer itself, I prefer to close this question. You may consider post this as a general question on Stackoverflow or even reddit. Let me know if I'm wrong.
