### ISSUE TITLE
Update README

### ISSUE THREAD

**Issue by AnthonyPorthouse** [rap2hpoutre/laravel-log-viewer#12]
The command `composer require rap2hpoutre/laravel-log-viewer` should be used in place of `composer require rap2hpoutre/laravel-log-viewer:0.2.*` as the former will resolve to the lastest stable version with any patch version e.g. `composer require rap2hpoutre/laravel-log-viewer:~0.2`

This will save having to update the README's installation instructions on every new release.

**Comment by rap2hpoutre** [comment]
Thanks !

**Comment by rap2hpoutre** [comment]
(merged)
