### ISSUE TITLE
Upgrade to bootstrap 4

### ISSUE THREAD

**Issue by rap2hpoutre** [rap2hpoutre/laravel-log-viewer#120]
Bootstrap 3 is a bit obsolete now. We should upgrade it to Bootstrap 4 (warning: datatables is configured for bootstrap 3 I think, we have to check that before)

_Side note: I can help/mentor/validate if someone want to tackle this issue._

**Comment by withArtur** [comment]
After one month of Bootstrap 4 stable, the 3ird is yet obsolete? 
Guys how many sites you develop?

**Comment by rap2hpoutre** [comment]
😄  "Obsolete" is barbaric, you are right! Sorry about that. 

Still, Laravel 5.6 is now shipped with bootstrap 4. So it's the new "standard" I guess.

**Comment by mattlibera** [comment]
i am actually working through this right now within a project of mine, and if i can abstract it back out to your package i'll be happy to share.

one thing we lose with bs4 is glyphicons - docs recommend using a 3rd party font library instead. do you have a preferred font library? i personally use fontawesome but that's just out of habit at this point. 😃

**Comment by rap2hpoutre** [comment]
Fontawesome is great, It's my default choice too. Maybe there are some better/lighter alternatives (but I don't know which one is good)...

**Comment by mattlibera** [comment]
sounds good to me! i'll dig in and see if i can get you an ETA. there are already libraries for datatables that support bs4 so that part is easy to drop in.

**Comment by mattlibera** [comment]
PR is in! happy to discuss anything / everything. #122

**Comment by rap2hpoutre** [comment]
Thanks!
