### ISSUE TITLE
Add comments (description) to config file

### ISSUE THREAD

**Issue by rap2hpoutre** [rap2hpoutre/laravel-log-viewer#125]
[This config](https://github.com/rap2hpoutre/laravel-log-viewer/blob/master/src/config/logviewer.php) option was added via [this PR](https://github.com/rap2hpoutre/laravel-log-viewer/pull/113). Still it's not documented, it could be great if we could add some comments to explain this config option (maybe with Taylor Otwell comments style!).

**Comment by mg-freelancer** [comment]
May I work on this feature ?

**Comment by rap2hpoutre** [comment]
Yes, of course!

2018-03-14 21:49 GMT+01:00 Mohamed G.Hafez <notifications@github.com>:

**Comment by elminson** [comment]
Hello @rap2hpoutre  can I work to extract all the "**pattern**" for the **preg_match_all** parameters?  I'm not sure if this is a good idea but having the "**patterns**" all over the class instead of having all the **patterns** on a class (or a config file)  for the **preg_match**.

**Comment by rap2hpoutre** [comment]
@elminson Thank you for your suggestion! If you want to refactor some code, you can try and send a PR. Be sure I will read it carefully, though _maybe I would not accept it_. So be prepared for this, I don't want to disappoint you! Keep in mind that the main goal of this package is to be simple (code and usage), so think about this when you create your PR.

**Comment by elminson** [comment]
Thanks @rap2hpoutre. All the time I keep in mind how to make code simple, reusable and readable. If you don't accept it is ok, I will try again until you like it :) lol. I will submit the PR in a few minutes.

**Comment by elminson** [comment]
@rap2hpoutre this is enough for this documentation? 
return [
    /*
     |--------------------------------------------------------------------------
     | Pattern and storage path settings
     |--------------------------------------------------------------------------
     |
     | The env key for pattern and storage path with a default value
     |
     */
    'pattern' => env('LOGVIEWER_PATTERN', '*.log'),
    'storage_path' => env('LOGVIEWER_STORAGE_PATH', 'logs'),
];

**Comment by elminson** [comment]
If the PR is ok then we can mark as solved(closed) this issue @rap2hpoutre

**Comment by rap2hpoutre** [comment]
Fixed via https://github.com/rap2hpoutre/laravel-log-viewer/pull/160
