### ISSUE TITLE
Hi Have problem with last update

### ISSUE THREAD

**Issue by avesgit** [rap2hpoutre/laravel-log-viewer#128]
Hi Have problem with last update. I dont see any records. My storage have 777 access right. I can access directly. But my laravel-log-viewer panel is empty

**Comment by rap2hpoutre** [comment]
OK you are right, I think I broke something in v0.14. Please use v0.13 I will fix it soon.

**Comment by rap2hpoutre** [comment]
Fixed! Update to v0.14.1. The problem was due to this commit https://github.com/rap2hpoutre/laravel-log-viewer/commit/47a428f7bb6aaa70bb26b5fb0b9be4a2c04cc2d9 and fixed via https://github.com/rap2hpoutre/laravel-log-viewer/commit/f5135771d0f1ae0078d95e3f8ea72a3fdd0d73df

Thanks!!

**Comment by avesgit** [comment]
Thanks for you very fast reaction
