### ISSUE TITLE
additional problem local.ERROR: The payload is invalid.

### ISSUE THREAD

**Issue by avesgit** [rap2hpoutre/laravel-log-viewer#129]
when i open today any log file i catch exception local.ERROR: The payload is invalid.
Log didn't open

**Comment by rap2hpoutre** [comment]
Links changed from base64 to Crypt (see https://github.com/rap2hpoutre/laravel-log-viewer/commit/cda89c06dc5331d06fab863d7cb1c4047ad68357). It *should* work, don't know why it fails. Could you give me some more context:
 - Laravel (or Lumen) version
 - Do you see a base64 (short) url when you click a link or an encrypted thing (long)?
 - Did it fail on a fresh installation of Laravel for you?

Thanks!

**Comment by avesgit** [comment]
1. 5.5 and 5.6
2 Yes logs?l=bGFyYXZlbC0yMDE4LTAzLTE1LmxvZw==
3. 5.5 old 5.6 2 days ago
4.
#0 /var/www/inettools.net/vendor/laravel/framework/src/Illuminate/Encryption/Encrypter.php(134): Illuminate\\Encryption\\Encrypter->getJsonPayload(NULL)
#1 /var/www/inettools.net/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(221): Illuminate\\Encryption\\Encrypter->decrypt('bGFyYXZlbC0yMDE...')
#2 /var/www/inettools.net/vendor/rap2hpoutre/laravel-log-viewer/src/controllers/LogViewerController.php(24): Illuminate\\Support\\Facades\\Facade::__callStatic('decrypt', Array)
#3 [internal function]: Rap2hpoutre\\LaravelLogViewer\\LogViewerController->index()
#4 /var/www/inettools.net/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(54): call_user_func_array(Array, Array)
#5 /var/www/inettools.net/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(45): Illuminate\\Routing\\Controller->callAction('index', Array)
#6 /var/www/inettools.net/vendor/laravel/framework/src/Illuminate/Routing/Route.php(212): Illuminate\\Routing\\ControllerDispatcher->dispatch(Object(Illuminate\\Routing\\Route), Object(Rap2hpoutre\\LaravelLogVi$
#7 /var/www/inettools.net/vendor/laravel/framework/src/Illuminate/Routing/Route.php(169): Illuminate\\Routing\\Route->runController()
#8 /var/www/inettools.net/vendor/laravel/framework/src/Illuminate/Routing/Router.php(658): Illuminate\\Routing\\Route->run()
#9 /var/www/inettools.net/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(30): Illuminate\\Routing\\Router->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#10 /var/www/inettools.net/vendor/ultraware/roles/src/Middleware/VerifyRole.php(39): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#11 /var/www/inettools.net/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Ultraware\\Roles\\Middleware\\VerifyRole->handle(Object(Illuminate\\Http\\Request), Object(Closure), 'admin')
#12 /var/www/inettools.net/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#13 /var/www/inettools.net/vendor/barryvdh/laravel-cors/src/HandleCors.php(36): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#14 /var/www/inettools.net/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Barryvdh\\Cors\\HandleCors->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#15 /var/www/inettools.net/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#16 /var/www/inettools.net/vendor/matthewbdaly/laravel-etag-middleware/src/ETag.php(24): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#17 /var/www/inettools.net/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Matthewbdaly\\ETagMiddleware\\ETag->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#18 /var/www/inettools.net/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#19 /var/www/inettools.net/app/Http/Middleware/LangMiddleware.php(26): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#20 /var/www/inettools.net/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): App\\Http\\Middleware\\LangMiddleware->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#21 /var/www/inettools.net/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#22 /var/www/inettools.net/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#23 /var/www/inettools.net/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\\View\\Middleware\\ShareErrorsFromSession->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#24 /var/www/inettools.net/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#25 /var/www/inettools.net/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(63): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#26 /var/www/inettools.net/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\\Session\\Middleware\\StartSession->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#27 /var/www/inettools.net/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#28 /var/www/inettools.net/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Re$
#29 /var/www/inettools.net/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\\Cookie\\Middleware\\AddQueuedCookiesToResponse->handle(Object(Illuminate\\Http\\Request), Object(Closur$
#30 /var/www/inettools.net/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#31 /var/www/inettools.net/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(59): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#32 /var/www/inettools.net/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\\Cookie\\Middleware\\EncryptCookies->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#33 /var/www/inettools.net/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#34 /var/www/inettools.net/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(102): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#35 /var/www/inettools.net/vendor/laravel/framework/src/Illuminate/Routing/Router.php(660): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#36 /var/www/inettools.net/vendor/laravel/framework/src/Illuminate/Routing/Router.php(635): Illuminate\\Routing\\Router->runRouteWithinStack(Object(Illuminate\\Routing\\Route), Object(Illuminate\\Http\\Request))
#37 /var/www/inettools.net/vendor/laravel/framework/src/Illuminate/Routing/Router.php(601): Illuminate\\Routing\\Router->runRoute(Object(Illuminate\\Http\\Request), Object(Illuminate\\Routing\\Route))
#38 /var/www/inettools.net/vendor/laravel/framework/src/Illuminate/Routing/Router.php(590): Illuminate\\Routing\\Router->dispatchToRoute(Object(Illuminate\\Http\\Request))
#39 /var/www/inettools.net/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(176): Illuminate\\Routing\\Router->dispatch(Object(Illuminate\\Http\\Request))

**Comment by rap2hpoutre** [comment]
It seems like you have an old version of the view. Could you run `php artisan cache:clear` then refresh the base page (without the payload) of the logs?

 (thanks for your time)

**Comment by avesgit** [comment]
i did that same

**Comment by avesgit** [comment]
i deleted old files new file open thx

**Comment by rap2hpoutre** [comment]
Great! Thank you for your help!

**Comment by avesgit** [comment]
need rename/delete file resources/views/vendor/laravel-log-viewer/log.blade.php
