### ISSUE TITLE
500 and memory exceed using it with Laradock

### ISSUE THREAD

**Issue by comlaterra** [rap2hpoutre/laravel-log-viewer#133]
Using the latest laradock version and just following The Readme, accessing to `/logs` 500 errors with a memory exceeded error at line 130 of the `LaravelLogViewer.php` file.

After that only 500.

Non interesting logs.

**Comment by rap2hpoutre** [comment]
Ok. Could you please list the file (with their size) in the log dir? (with `ll` or something like that). Also could you tell me what is your current `memory_limit`?

**Comment by rap2hpoutre** [comment]
Closed (lack of activity)
