### ISSUE TITLE
Daily storage logs not working for lumen 5.5.*.

### ISSUE THREAD

**Issue by serdarsaygili** [rap2hpoutre/laravel-log-viewer#137]
Encrypter.php -> getJsonPayload waits payload to be json_decodeable bash64 encrypted data.
But the payload comes as base64 encoded string of log file name (lumen-2018-04-19.log).
So selecting log file throws an invalid payload exception.

**Comment by rap2hpoutre** [comment]
What version of laravel log viewer do you use?

Le jeu. 19 avr. 2018 11:42, Serdar Saygılı <notifications@github.com> a
écrit :

**Comment by Cyclops0571** [comment]
I tried 0.14.3 to 0.11.2 one by one. 0.11.2 worked others did not worked. I was using 0.10.* and when I see the secury issue I tried to update package but it did not worked out.

**Comment by rap2hpoutre** [comment]
Thank you! Maybe there is something about view cache (not sure though). Could you remove everything in `storage/framework/views/` then try again?

**Comment by rwattogl** [comment]
Confirm I am getting the same issue with Laravel 5.6
"laravel/framework": "5.6.*",
"rap2hpoutre/laravel-log-viewer": "~0.14",

I also tested with ~0.11. It was definitely working previously, but some update since (possibly to magento?) has broken it.

**Comment by rap2hpoutre** [comment]
@rwattogl Could you try to reload the views cache? Just run:

```
php artisan view:clear
```

**Comment by rwattogl** [comment]
Sorry, forgot to mention I had already done that (and have tried manually clearing the directories too). We update new versions of the site automatically via ansible and clear all the caches on updating, so any of those are unlikely to be the issue. If you're not able to reproduce the issue yourself, I should have some time to investigate later this week and will report back.

**Comment by rwattogl** [comment]
Ah, you're completely correct - I forgot we had a customised view in there, which hasn't been updated in line with the latest version of the code. I replaced the base64 functions with the new style references to  \Illuminate\Support\Facades\Crypt::encrypt and it all works perfectly again. It could be worth @Cyclops0571 checking in there as well, especially if they've been jumping around versions and had also published that view.

**Comment by rap2hpoutre** [comment]
@Cyclops0571 Did it solved your problem?

**Comment by eternal365** [comment]
@rap2hpoutre +1 for

`php artisan view:clear`

**Comment by rap2hpoutre** [comment]
It seems it's OK now.
