### ISSUE TITLE
Log Location customisable

### ISSUE THREAD

**Issue by afilias-gtawaf** [rap2hpoutre/laravel-log-viewer#139]
Hello,
  Is there a way to customise where to fetch logs from?
  I see in code storage('log') if that could be changed into configuration with  default storage('log')

Thanks

**Comment by rap2hpoutre** [comment]
Thank you for your contribution! Yes it's a good idea. Feel free to submit a PR for this need.

**Comment by elminson** [comment]
@rap2hpoutre  could be something like this 
`        $storage_path = function_exists('config') ? config('logviewer.storage_path', 'logs') : 'logs';
`
and in logviewer.php (config)
`    'storage_path' => env('LOGVIEWER_STORAGE_PATH', 'logs'),
`
I have the code ready i will submit the PR in a few

**Comment by elminson** [comment]
Should we mark this issue as solved(closed)? @rap2hpoutre

**Comment by rap2hpoutre** [comment]
Yes! Thank you!

**Comment by rap2hpoutre** [comment]
Fixed via https://github.com/rap2hpoutre/laravel-log-viewer/pull/159
