### ISSUE TITLE
ErrorException - 'Undefined offset: 0'

### ISSUE THREAD

**Issue by peppeocchi** [rap2hpoutre/laravel-log-viewer#14]
This exception is thrown if no log file exists yet.

It should be a quick fix, this is the spot
https://github.com/rap2hpoutre/laravel-log-viewer/blob/master/src/Rap2hpoutre/LaravelLogViewer/LaravelLogViewer.php#L53

If you'd like I can submit a pull request.

PS: this log viewer is really cool!

**Comment by AnthonyPorthouse** [comment]
I noticed this when I was setting up the test environment for overriding views in 4.2, its sort of self fixing though as you'll only ever see it once, then it logs the error and it fixes itself.

**Comment by peppeocchi** [comment]
Yes, I find it very annoying because every time I deploy to elastic beanstalk (the logs folder is in the gitignore, I have no need to save the log files in -eg- an s3 bucket and I'm happy to have no logs every time I deploy), so the first thing I do after a deploy is checking the logs = first log error is the logviewer itself :D

**Comment by rap2hpoutre** [comment]
@peppeocchi :D
Ok, you can submit a pull request for this if you want ! Thank you for contributing :)

**Comment by rap2hpoutre** [comment]
Ok resolved in v0.2.1 (thank you !)
