### ISSUE TITLE
Add scrolling to list of log files on left hand side

### ISSUE THREAD

**Issue by rajjanorkar** [rap2hpoutre/laravel-log-viewer#143]
It will be awesome to add scrolling on this view for long list of files.

![image](https://user-images.githubusercontent.com/7500838/41198869-6ebab8f6-6ccb-11e8-91fb-811cfb6c7dad.png)

**Comment by rap2hpoutre** [comment]
Thank you for your contribution! What do you mean by "scrolling"? Do you want to "hide" the last entries and add a scroll bar? Add a pager system for the file names? Something else?

**Comment by rajjanorkar** [comment]
The list on left hand side is very long in my case 90 log files.

so it would be great if we can display how much we can fit on page and hide others and add scroll bar to see other entries on scroll.

**Comment by elminson** [comment]
Hello @rajjanorkar and @rap2hpoutre I just finish this, I will create a PR soon 

:)

**Comment by rajjanorkar** [comment]
@elminson  thank you so much thats what exactly i wanted it.

**Comment by elminson** [comment]
Your welcome @rajjanorkar, now @rap2hpoutre have to approve the PR 👍

**Comment by rap2hpoutre** [comment]
Thank you @elminson for your help! I added some comments in the PR (https://github.com/rap2hpoutre/laravel-log-viewer/pull/167).

@rajjanorkar Sorry for the (long) delay, hopefully @elminson helped you!

**Comment by elminson** [comment]
@rap2hpoutre  Comments addressed 👍

**Comment by rap2hpoutre** [comment]
Ok thank you @elminson !!
