### ISSUE TITLE
Ability to read non-standard format logs

### ISSUE THREAD

**Issue by DivineOmega** [rap2hpoutre/laravel-log-viewer#144]
I'm currently code similar to the following in my Kernel schedule method to write out the results of an artisan command to a file in the log directory.

```php
$schedule->command('foo:bar')
            ->dailyAt('01:00')
            ->sendOutputTo(storage_path('/logs/'.date('Y-m-d').'-foo-bar.log'));
```

Since this is just output from an artisan command, it does not match the standard format that would be output if I used the various `Log` facade methods.

When using this package to attempt to view the log, it shows the file name, but when clicked it shows no content in the main panel. It would be handy if the log viewer could show the content of the log even if the format is not as expected.

The 'Level', 'Context', and 'Date' columns would have to remain unpopulated, but the 'Content' could should a new row for each line of text in the log file.

**Comment by rap2hpoutre** [comment]
Thank you for your contribution! This is a great suggestion, feel free to submit a PR if you want! (I could code it myself too, as you wish)
