### ISSUE TITLE
Reduce `LaravelLogViewer` class complexity

### ISSUE THREAD

**Issue by rap2hpoutre** [rap2hpoutre/laravel-log-viewer#148]
There is a bunch of `if`, `for`, etc. in this file: 

[`src/Rap2hpoutre/LaravelLogViewer/LaravelLogViewer.php`](https://github.com/rap2hpoutre/laravel-log-viewer/blob/master/src/Rap2hpoutre/LaravelLogViewer/LaravelLogViewer.php)

It's now a spaghetti, ugly code. It add to be fixed, to reduce complexity (split in methods, refactor, maybe inherit, add trait and composition).

**Comment by elminson** [comment]
@rap2hpoutre  what do you think about extract all the setters and getters as inherit class? I will love to start this enhancement.

**Comment by elminson** [comment]
I just send a PR with function `getArrayLog` reusing the log array creation and `setFileAll` to make sure $file is set

**Comment by elminson** [comment]
@rap2hpoutre any comment in the PR?

**Comment by rap2hpoutre** [comment]
Thank you! I answered in the PR #161
