### ISSUE TITLE
Customizable controller

### ISSUE THREAD

**Issue by larsbo** [rap2hpoutre/laravel-log-viewer#149]
A nice feature would be a config file where you can define the controller class to allow the extension of the original one (e.g. to support some kind of authorization or customization).

The packages of spatie oftes have such an option, e.g.
https://github.com/spatie/laravel-fractal/blob/master/config/fractal.php#L26

**Comment by rap2hpoutre** [comment]
Thank you for your contribution!

As a workaround, you can extends the original controller and add your own rules : 

```php
class MyLVController extends \Rap2hpoutre\LaravelLogViewer\LaravelLogViewerController {
    public function index()
    {
        // do some stuff, then:
        parent::index()
    }
}
```

Then use your controller in your route:

```php
Route::get('logs', '\Path\To\MyLVController@index');
```

One other approach could be to use middleware, if you need to "support some kind of authorization":

```php
Route::get(
    'logs', 
    '\Rap2hpoutre\LaravelLogViewer\LogViewerController@index'
)->middleware('auth_or_something_else');
```

**Comment by larsbo** [comment]
Oh yes, thanks a lot for pointing me in the right direction! I forgot that the controller can simply be changed in the routes file 😄
