### ISSUE TITLE
Rate limiting

### ISSUE THREAD

**Issue by sdeering** [rap2hpoutre/laravel-log-viewer#151]
When there is an error message logged every 2 seconds (due to an error being thrown by our code) we noticed our CPU spiking high.

Is there a way to rate limit the logs that are being written? or a way to queue those logs and then write in 1 go, say every 10 seconds?

**Comment by rap2hpoutre** [comment]
Hi @sdeering! Thank you for your contribution! This package is only a log _viewer_, it can't handle rate limits nor the way logs are written/treated. Maybe you could check on reddit or stackoverflow, not sure where to ask...

**Comment by sdeering** [comment]
Ok thanks yeah need to further investigate this,
