### ISSUE TITLE
login-credentials

### ISSUE THREAD

**Issue by DrackThor** [rap2hpoutre/laravel-log-viewer#165]
Hi there,
after installing the software to my existing laravel project (which seemed to work fine) I want to access the xxx/logs site, but I get asked for login credentials. Neither do I know those credentials, nor do my user-credentials (to my project's user account) work.
Did I do something wrong or prbly just miss something in the docu?

regards

**Comment by elminson** [comment]
Hello, @DrackThor thanks for you for share this. 

Please provide a screenshot, of the login credentials screen. 
you can post any log, this can help us to figure out what is happening and in what level.

**Comment by rap2hpoutre** [comment]
Hi @DrackThor! It seems there is no connection with the log viewer itself: this lib does not introduce anything about authentication (you have to manage it yourself). You could check if you configured some middleware on your side (you could have a look at your routes files).

**Comment by DrackThor** [comment]
Hi @rap2hpoutre @elminson ,
thanks for your reply. I figured that indeed the lib works perfectly when I use a different uri than '/logs'.
It probably clashes with some other installed libs - thanks for your help! :)

**Comment by rap2hpoutre** [comment]
You are welcome!
