### ISSUE TITLE
reset() expects parameter 1 to be array, null given what's wrong with this?

### ISSUE THREAD

**Issue by phpapi** [rap2hpoutre/laravel-log-viewer#166]
I got this error after git pull in my server, my local is fine. That's something file permissions question?

`ErrorException (E_WARNING)
reset() expects parameter 1 to be array, null given
`

**Comment by elminson** [comment]
Thanks Carey for you report. Can you elaborate what parameter are you
passing to reset(), line, screenshot ? Please remove any sensitive
information. Thanks.

**Comment by elminson** [comment]
The call for `reset` is on line 70 from file `/src/controllers/LogViewerController.php`
`$firstLog = reset($data['logs']);`
this reference to `$data['logs'])` filled on line 57 
```php
        $data = [
            **'logs' => $this->log_viewer->all(),**
            'folders' => $this->log_viewer->getFolders(),
            'current_folder' => $this->log_viewer->getFolderName(),
            'folder_files' => $folderFiles,
            'files' => $this->log_viewer->getFiles(true),
            'current_file' => $this->log_viewer->getFileName(),
            'standardFormat' => true,
        ];
```
this mean that `$this->log_viewer->all()`  is returning null.

calling all from `$this->log_viewer = new LaravelLogViewer();` 
Finally  public function all() from class `LaravelLogViewer()` is retuning null and not an array, 

you can check
1) print out `$data` and check the content (logs element must be an array even if is empty)
2) permission on the store folder
3) check the /var/log errors_log(apache or ngnix) and see if have more details about the error. 

please post any update on this issue.

**Comment by rap2hpoutre** [comment]
@phpapi OK, I close it for now, feel free to leave a comment if something went wrong!

**Comment by acodercat** [comment]
0.21.0 hava ```reset() expects parameter 1 to be array ```

**Comment by rap2hpoutre** [comment]
@acodercat Thank you for your contribution! Could you provide the whole error backtrace please?
