### ISSUE TITLE
InvalidArgumentException in compiled.php line 12896: No hint path defined for [laravel-log-viewer]

### ISSUE THREAD

**Issue by ravaboard** [rap2hpoutre/laravel-log-viewer#17]
Im a newbie with laravel, but did all as in the README of this package and when I go to http://myapp/logs I get this error:

InvalidArgumentException in compiled.php line 12896: No hint path defined for [laravel-log-viewer]

Any ideas on why this happens?

Thanks.

**Comment by rap2hpoutre** [comment]
Hi,
What's your laravel version ? (it will help me to understand your problem) Can you try in a local environnement (with debug "true") ?

**Comment by ravaboard** [comment]
Here it is on my test server: http://178.62.83.46/logs

Laravel version - latest.

**Comment by rap2hpoutre** [comment]
OK, I tried different things on fresh installs and I think I understood your problem.

Did you add `'Rap2hpoutre\LaravelLogViewer\LaravelLogViewerServiceProvider'` in `config/app.php` file (in `providers` section, line 147 on a fresh install) ? I hope it will solve your problem

**Comment by ravaboard** [comment]
Thanks, your extension is awesome!

**Comment by rap2hpoutre** [comment]
:)

**Comment by snoyface** [comment]
Using newest version installed, added 
`Rap2hpoutre\LaravelLogViewer\LaravelLogViewerServiceProvider' in config/app.php` Using in local environment.


 Still recieving error `local.ERROR: exception 'InvalidArgumentException' with message 'No hint path defined for [laravel-log-viewer].`

**Comment by rap2hpoutre** [comment]
OK what is your laravel version and your log viewer version?

**Comment by rap2hpoutre** [comment]
On a laravel 5.1 install you should write `Rap2hpoutre\LaravelLogViewer\LaravelLogViewerServiceProvider::class,`

**Comment by snoyface** [comment]
Laravel 5.1, most recent stable build (0.4.3). 

Thank you, that did it!

**Comment by rap2hpoutre** [comment]
Cool!

**Comment by rap2hpoutre** [comment]
@xavierpernalete

Did you add 'Rap2hpoutre\LaravelLogViewer\LaravelLogViewerServiceProvider' in config/app.php file (in providers section, line 147 on a fresh install) ?

After that, run `php artisan config:cache` if it still does not work and you use config:cache

**Comment by xavierpernalete** [comment]
Thank you I had to run  command artisan
