### ISSUE TITLE
Connection reset after cleaning the log file

### ISSUE THREAD

**Issue by thureos** [rap2hpoutre/laravel-log-viewer#172]
Hello,

First of all, thanks for this amazing tool.

So, when I click on the clean file button, the page refreshed and it didn't show me anything, Browser showed me "Connection reset".

If I go back in browser history and hit refresh, the viewer will show correctly with 1 empty line.

Tested on Laravel 5.6.

Thanks!

**Comment by elminson** [comment]
Hello, @thureos  I will try to replicate the issue and then try t fix it.

**Comment by elminson** [comment]
I just test it, clean installation Laravel 5.6 and is not showing "Connection Reset"
can you please provide more info ( screenshot, log files, any other resources) to see why this is happing

**Comment by rap2hpoutre** [comment]
@thureos Did you fixed your issue? Since this issue is a bit old, I close it, feel free to re-open if you still have problem.
