### ISSUE TITLE
Default value of 'storage_path' config option should be altered.

### ISSUE THREAD

**Issue by qqjt** [rap2hpoutre/laravel-log-viewer#174]
Hi,
I'm using laravel-log-viewer with laravel 5.7 and I see no logs, even though I've got something in `storage/logs/laravel.log`. I found it to be a config flaw in ` logviewer.php`:
```
'storage_path' =>` env('LOGVIEWER_STORAGE_PATH', 'logs')`
```
should be
```
'storage_path' => env('LOGVIEWER_STORAGE_PATH', storage_path('logs')),
```

**Comment by rap2hpoutre** [comment]
Thank you for your contribution! Fixed, available in v0.22.1
