### ISSUE TITLE
v22.1 - Conflict with boostrap dropdown or collapse

### ISSUE THREAD

**Issue by esipavicius** [rap2hpoutre/laravel-log-viewer#179]
Hi,

When I have menu like this:
```
...
<ul class="nav navbar-nav navbar-left">
    <li class="dropdown">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown">User <span class="caret"></span></a>
        <ul class="dropdown-menu">
            <li><a href="{{ route('backend.users.index') }}">Users</a></li>
            <li><a href="{{ route('backend.role.index') }}">Roles</a></li>
        </ul>
    </li>
</ul>
...
```

And opened log view page it can not open drowpdown menu. It's adding `.show` class near `.dropdown` so when I click it should be `dropdown open`, not `dropdown open show`. When I click again(close it) its become `dropdown open`. Again(open) `dropdown open show`...

**Comment by rap2hpoutre** [comment]
Hi, thank you for your contribution! The default view file in LaravelLogViewer is a standalone view, it should not be mixed with other views. Are you using your own blade file for displaying the log viewer? If so, you will have to fix it yourself (it may be a conflict between bootstrap version)
