### ISSUE TITLE
Question for you 

### ISSUE THREAD

**Issue by laravelcoder** [rap2hpoutre/laravel-log-viewer#183]
I want to change the default number of records from 10 to 50 where can i do this in your code. can you direct me to the right file please?

Also is there a config file for this package?

**Comment by Cherry-Pie** [comment]
@laravelcoder 
Try to add DataTable option `"pageLength": 50,` here: https://github.com/rap2hpoutre/laravel-log-viewer/blob/fd0821b073771f3e7256664417055a8bbb091059/src/views/log.blade.php#L198


[DataTables manual reference](https://datatables.net/reference/option/pageLength)

**Comment by laravelcoder** [comment]
Thank you
