### ISSUE TITLE
No supported encrypter found. The cipher and / or key length are invalid.

### ISSUE THREAD

**Issue by listen-rain** [rap2hpoutre/laravel-log-viewer#185]
No supported encrypter found. The cipher and / or key length are invalid. (View: /www/haoweilai/chinese_classroom/resources/views/vendor/laravel-log-viewer/log.blade.php)

**Comment by rap2hpoutre** [comment]
Hi and thank you for your contribution! Please have a look at https://github.com/rap2hpoutre/laravel-log-viewer/issues/164 https://github.com/rap2hpoutre/laravel-log-viewer/issues/126 and https://stackoverflow.com/questions/30344141/lumen-micro-framework-php-artisan-keygenerate if you are using lumen)

**Comment by yevhenlisovenko** [comment]
Hi,

I have the similar issue in Lumen, APP_KEY already there (integrated key:generate command).

Any ideas how to fix this?

Thanks.

```

(2/2) ErrorExceptionUndefined index: key (View: /app/vendor/rap2hpoutre/laravel-log-viewer/src/views/log.blade.php)
--
in EncryptionServiceProvider.php line 42
at CompilerEngine->handleViewException(object(ErrorException), 0)in PhpEngine.php line 45

(1/2) ErrorExceptionUndefined index: key
--
in EncryptionServiceProvider.php line 42



```

**Comment by yevhenlisovenko** [comment]
Found a solution. Maybe it will help somebody...

Just need to add to config/app.php
```
    'key' => env('APP_KEY'),

    'cipher' => 'AES-256-CBC',
```

**Comment by rap2hpoutre** [comment]
Thank you @yevhenlisovenko !
