### ISSUE TITLE
Why does log files are converted to zip files?

### ISSUE THREAD

**Issue by vishalmandora** [rap2hpoutre/laravel-log-viewer#191]
I'm not sure is it issue or feature but it automatically converts log files into zip file after few days. why does this happen?

**Comment by rap2hpoutre** [comment]
Hi, thank you for your contribution! It seems this issue is not a viewer issue. Laravel log viewer only provides a view tool for logs, it does not affect how it works (how they're stored, rotated, zipped, etc.). You could have a look at laravel log's documentation
