### ISSUE TITLE
Support different formatter

### ISSUE THREAD

**Issue by ahren-condos-ca** [rap2hpoutre/laravel-log-viewer#192]
I have overridden the default formatter as follows:

`// create a record log channel
$this->record_log = new Logger('RECORD_SYNC');`
`$record_handler = new StreamHandler("/var/www/api/storage/logs/record_sync.log",100);`
`$record_handler->setFormatter(new LineFormatter("%datetime% [%level_name%] %message%\n"));`

For Better readability we tailing on a log... but now these don't load or show via your log viewer.

Is there a way I can change a config file or something to make your log view to support a non-standard LineFormatter?

**Comment by rap2hpoutre** [comment]
This log viewer is an old spaghettiesque thing that I still maintain, but I do not promote it anymore nor add new features.
