### ISSUE TITLE
"Exception: No such log file" when deleting/cleaning/downloading

### ISSUE THREAD

**Issue by Ekrow** [rap2hpoutre/laravel-log-viewer#193]
Whenever I want to use the bottom actions "clean file", "download file" and "delete file" I get "Exception: No such log file" thrown from pathToLogFile()-function.

I've noticed that `$file` and `$logsPath` are different, because `$file` gets the directory appended. However the directory is already in `$file` before that.

e.g.

$file = "import/import/import-2019-04-02.log"
$logsPath= "import/import-2019-04-02.log"

Directory Structure of log files is the following:

storage/logs
..|-import
....|-import-2019-04-02.log
....|-import-2019-04-03.log
..|-login
..|-task
..|-mail

I'm currently using the default log.blade.php from inside the vendor directory for my view. When I changed
`<a id="delete-log" href="?del={{ \Illuminate\Support\Facades\Crypt::encrypt(**$current_folder ? $current_folder . "/" . $current_file : $current_file**) }}[...]`

to

`<a id="delete-log" href="?del={{ \Illuminate\Support\Facades\Crypt::encrypt(**$current_file**) }}[...]`

it works however. Essentially I'm removing the folder from the file-parameter. Any ideas what causes this on my end? Is it the structure of the log directory?

Edit: Log files in the root directory "logs" are fine however.

**Comment by Frewen** [comment]
I also encountered the same problem.

**Comment by rap2hpoutre** [comment]
Hi @Ekrow & @Frewen ! Thank you for your contribution! Sorry for late answer.

I fixed the problem thanks to your issue. It's now available in v1.2.1.

Just update to this version and it will be fixed!

**Comment by rap2hpoutre** [comment]
Resolved.
