### ISSUE TITLE
Json data

### ISSUE THREAD

**Issue by 1benayatei** [rap2hpoutre/laravel-log-viewer#195]
**How get json data ?**

**Comment by rap2hpoutre** [comment]
Hi, thank you for your contribution. Could you please post an example about what you want to achieve?

**Comment by 1benayatei** [comment]
> Hi, thank you for your contribution. Could you please post an example about what you want to achieve?

Hi, I want to be out of view and only raw data. I want to show in custom ui.

**Comment by rap2hpoutre** [comment]
This log viewer cannot display raw JSON. You should use an alternative (Nova, https://github.com/ARCANEDEV/LogViewer, etc.)
