### ISSUE TITLE
Set config for lumen

### ISSUE THREAD

**Issue by lhq0826** [rap2hpoutre/laravel-log-viewer#199]
https://github.com/rap2hpoutre/laravel-log-viewer/blob/ba8e645dda959c9cc679f3bbb3f1bd271cc02e56/src/Rap2hpoutre/LaravelLogViewer/LaravelLogViewerServiceProvider.php#L33

```
if ($this->app instanceof LumenApplication) {
     $this->app->configure('logviewer');
}
```

**Comment by rap2hpoutre** [comment]
Hi, thank you for your contribution. I'm not sure to understand the purpose of this issue... What do you want to do? How can I help?

**Comment by lhq0826** [comment]
Hi，I want to load logviewer config When use lumen framework;

**Comment by yanuaraditia** [comment]
Here from [docs](https://github.com/rap2hpoutre/laravel-log-viewer/blob/master/README.md)

Install via composer
`composer require rap2hpoutre/laravel-log-viewer`

Add the following in bootstrap/app.php:
`$app->register(\Rap2hpoutre\LaravelLogViewer\LaravelLogViewerServiceProvider::class);`

Explicitly set the namespace in app/Http/routes.php:
```
$router->group(['namespace' => '\Rap2hpoutre\LaravelLogViewer'], function() use ($router) {
    $router->get('logs', 'LogViewerController@index');
});
```
