### ISSUE TITLE
Converting context to human readable

### ISSUE THREAD

**Issue by Ortix92** [rap2hpoutre/laravel-log-viewer#2]
The second argument for Log::info() (or any other log) takes the context array. Would you be able to manage to implement a more human readable form instead of a json representation of the array?

I currently add a new line to my message so it drops the context to a new line. This way it will be caught by `$log['stack']` and expanded when the search button is pressed.

**Comment by rap2hpoutre** [comment]
I think it's a little more readable now (line breaks, etc.)
