### ISSUE TITLE
Not able to change the LOGVIEWER_STORAGE_PATH

### ISSUE THREAD

**Issue by r4rishabhgupta** [rap2hpoutre/laravel-log-viewer#210]
I change the LOGVIEWER_STORAGE_PATH="/opt/application/logs/" in .env file but it showing log files from storage/log.
Any Help Will Be Appreciated.

Thanks

**Comment by r4rishabhgupta** [comment]
I think there is a minor bug in config/logviewer.php
$this->storage_path = function_exists('config') ? config('logviewer.storage_path') : storage_path('logs');

**Comment by r4rishabhgupta** [comment]
Problem solved we need to copy copy logviewer,php from rap2hpouter's config to laravel's config folder and add new location to .env file

**Comment by rap2hpoutre** [comment]
Sorry for the lack of answer. I'm glad it works now!
