### ISSUE TITLE
 Is there an example of adding lumen authentication via route? 

### ISSUE THREAD

**Issue by lucenarenato** [rap2hpoutre/laravel-log-viewer#211]
Is there an example of adding lumen authentication via route?
Authenticate or Middleware?

Best regards Renato Lucena.

**Comment by rap2hpoutre** [comment]
Hi @lucenarenato ! Sorry for (super) late answer 😱. Unfortunately, there are currently no example of adding lumen authentication via route.

Still, currently ≈2k public packages officially uses this log viewer (https://github.com/rap2hpoutre/laravel-log-viewer/network/dependents?package_id=UGFja2FnZS01NDg0NTIxMzQ%3D) so you could have a look to some of them to check how they are adding lumen authentication via route

**Comment by lucenarenato** [comment]
Consegui resolver, Obrigado!
