### ISSUE TITLE
PHP 7.4 - Passing glue string is deprecated

### ISSUE THREAD

**Issue by FrankFlow** [rap2hpoutre/laravel-log-viewer#215]
After upgrade to PHP7.4 It returns this error:

join(): Passing glue string after array is deprecated. Swap the parameters (View: {WEBSITEPATH}/vendor/log-viewer/bootstrap-4/show.blade.php)

**Comment by ramonchristophermorales** [comment]
Anyone looking at this? Got the same issue

**Comment by MWA-NASMO** [comment]
Hello having the same issue ! :-(

**Comment by rap2hpoutre** [comment]
It seems you have a problem with another package (which has been fixed since): https://github.com/nealmegh/phdclub/blob/master/resources/views/vendor/log-viewer/bootstrap-4/show.blade.php

This package does not use `join`.
