### ISSUE TITLE
Adding additional path/s

### ISSUE THREAD

**Issue by DubStepMad** [rap2hpoutre/laravel-log-viewer#219]
Hi, I was wondering if there is any simple way of adding additional paths?

Otherwise I believe I might just have to edit the package to suit my needs but maybe this could be an extra feature.

**Comment by rap2hpoutre** [comment]
Hi @DubStepMad , sorry for late answer. You could actually adding multiple path in two steps

### Step 1

Publish configuration file:

```
php artisan vendor:publish \
  --provider="Rap2hpoutre\LaravelLogViewer\LaravelLogViewerServiceProvider"
```

### Step 2
Edit configuration file and replace this:

```
'storage_path'  => env('LOGVIEWER_STORAGE_PATH', storage_path('logs')),
```

By this:

```
'storage_path'  => env('LOGVIEWER_STORAGE_PATH', ['all', 'your', 'directories']),
```
