### ISSUE TITLE
Use cookies or local storage to remember entry count per page

### ISSUE THREAD

**Issue by briedis** [rap2hpoutre/laravel-log-viewer#22]
You could use cookies or local storage to remember entry count per page.

**Comment by rap2hpoutre** [comment]
Can you explain a little more? I'm not sure I understand why.

**Comment by briedis** [comment]
This is reset to 10 every time I reload the page, but I usually view 25 logs per page.

![](https://ziedlejas.lv/screenshots/img.2015.04.09.dzN6JX.png)

**Comment by rap2hpoutre** [comment]
Ok

**Comment by rap2hpoutre** [comment]
Resolved in v0.2.3 (run `composer update`)

**Comment by briedis** [comment]
Hmm, could be a new bug:
https://ziedlejas.lv/screenshots/img.2015.04.10.MYnNyT.png

I'm failing to expand logs..

**Comment by rap2hpoutre** [comment]
Oops :/

**Comment by rap2hpoutre** [comment]
Quick fix in v0.2.4 (I failed to replicate the bug, so it's just a try)
Can you retry ?

**Comment by briedis** [comment]
Looks like it works, thanks! :)

**Comment by rap2hpoutre** [comment]
Phew!
