### ISSUE TITLE
[Question] laravel 7 support

### ISSUE THREAD

**Issue by hmrneves1** [rap2hpoutre/laravel-log-viewer#226]
hello, will you support laravel 7 in this package? because when we try to install, composer gives tons of errors. Best regards

**Comment by rap2hpoutre** [comment]
Available in v1.4.0 (thanks to @dtvmedia 🎉)

See: #225

cc @rjsworking @v-stein @dannetstudio @mbarlund @ismaail @HELMAB @pedroloureiro82

**Comment by hmrneves1** [comment]
Thank you for your availability.

Best regards

A quinta, 5/03/2020, 20:42, Raphaël Huchet <notifications@github.com>
escreveu:
