### ISSUE TITLE
Broken layout

### ISSUE THREAD

**Issue by rikiless** [rap2hpoutre/laravel-log-viewer#228]
When longer name of log file used it will broke the layout.
<img width="1552" alt="Screenshot 2020-03-26 at 09 52 07" src="https://user-images.githubusercontent.com/589851/77627628-7a185e80-6f47-11ea-950e-e83e681c6d9f.png">

Browser Width: 1440px

Similar to #114.

**Comment by rap2hpoutre** [comment]
Fixed via #239 thanks to @DevDHera 

Available in v1.6.1
