### ISSUE TITLE
Use overflow:auto container for stack trace element

### ISSUE THREAD

**Issue by briedis** [rap2hpoutre/laravel-log-viewer#23]
Sometimes the log/stacktrace is pretty wide, and when I expand it, I cannot collapse it without scrolling sideways, because the button moves out of the visible area (and it's on a 1920px wide screen)
![Screenshot](https://ziedlejas.lv/screenshots/img.2015.04.09.YNJEKy.png)

I suggest wrapping the stack trace in a separate element and overflow:auto it, so the main layout doesn't expand more than needed.

**Comment by rap2hpoutre** [comment]
Ok it works with `white-space: pre-wrap`
Resolved in v0.2.7
Thanks :) !
