### ISSUE TITLE
After running a composer update, latest version does not work. 

### ISSUE THREAD

**Issue by timothymarois** [rap2hpoutre/laravel-log-viewer#231]
Ran a `composer update` today. Now the log viewer has a 500 error itself.

**Comment by timothymarois** [comment]
`v1.5.1`

**Comment by timothymarois** [comment]
Controller namespace has been modified in the new version, this was not updated in the readme, and is a dangerous thing to do during a regular update. 

New namespace: 
`\Rap2hpoutre\Controllers\LogViewerController@index`

Previous namespace: 
`\Rap2hpoutre\LaravelLogViewer\LogViewerController@index`

**Comment by DjeeBay** [comment]
@timothymarois see [#230](https://github.com/rap2hpoutre/laravel-log-viewer/issues/230)

**Comment by rap2hpoutre** [comment]
See: https://github.com/rap2hpoutre/laravel-log-viewer/issues/230

(again, sorry)

**Comment by timothymarois** [comment]
@rap2hpoutre No worries. thanks for the update!
