### ISSUE TITLE
Exceprion if log folder is empty

### ISSUE THREAD

**Issue by peyobr** [rap2hpoutre/laravel-log-viewer#24]
exception 'ErrorException' with message 'preg_match_all() expects parameter 2 to be string, array given'
in /var/www/html/app/public/vendor/rap2hpoutre/laravel-log-viewer/src/Rap2hpoutre/LaravelLogViewer/LaravelLogViewer.php:73

Thank you. (y)

**Comment by rap2hpoutre** [comment]
Thanks ! Resolved in v0.2.5 (run `composer update`)
