### ISSUE TITLE
Allow to download log files

### ISSUE THREAD

**Issue by briedis** [rap2hpoutre/laravel-log-viewer#25]
Sometimes it's easier to view log file a notepad, for searching, etc. Maybe it would be useful, if I could download a log file with a click :)

What do you think about this feature?

**Comment by rap2hpoutre** [comment]
It's a good idea, but I don't know where I should display this feature

**Comment by rap2hpoutre** [comment]
Any idea ?

**Comment by briedis** [comment]
I don't know, we need an artist :D

Maybe something like this? https://ziedlejas.lv/screenshots/img.2015.05.07.01ADAk.png

**Comment by TheShiftExchange** [comment]
Yeah - this would be super useful. I agree with Briedis screenshot - just a 'download log file' link (or button) in the view is all you need.

**Comment by rap2hpoutre** [comment]
OK !

**Comment by rap2hpoutre** [comment]
Ok, done! You can update to v0.3.0 :)
