### ISSUE TITLE
Needs HTML Encoding in place

### ISSUE THREAD

**Issue by Hawkeye66** [rap2hpoutre/laravel-log-viewer#27]
Needs htmlentities() (or similar) wrapped around at least the output of $log['stack']... otherwise "bad things" happen... :-)

**Comment by rap2hpoutre** [comment]
Ok, thanks.

`{{ trim($log['stack']) }}` is [already escaped](https://github.com/rap2hpoutre/laravel-log-viewer/blob/master/src/views/log.blade.php#L82).
According to [documentation](http://laravel.com/docs/5.0/templates#other-blade-control-structures),  everything within `{{ }}` is escaped, if I want to unescape, I need to write `{!! trim($log['stack']) !!}`

Did I miss something ?

**Comment by Hawkeye66** [comment]
That's not the behaviour using Laravel 4.x. Double {{}} does NOT escape,
you have to use triple {{{}}} in 4.x (see
http://laravel.com/docs/4.2/templates) or else - and for safety - wrap it
in htmlentities() regardless.

Nice package by the way - just the above took me ages to work out why
strange things were happening! One of my log messages had "<style>" in the
body and hence everything after it was being treated oddly!

**Comment by rap2hpoutre** [comment]
Oops. Sorry about that :/
Thanks to you :), I fixed it, it's OK now with v0.2.8 (just run `composer update`)
