### ISSUE TITLE
Unable to open log viewer due to lack of memory

### ISSUE THREAD

**Issue by libern** [rap2hpoutre/laravel-log-viewer#29]
production.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Allowed memory size of 134217728 bytes exhausted (tried to allocate 153967073 bytes)' in /srv/www/someline.com/someline/vendor/laravel/framework/src/Illuminate/Filesystem/Filesystem.php:34

==========

I think the problem is underlying that the log files are large in size, if you load them all in one time, it will not able to display.

Could you advice some solutions?

**Comment by rap2hpoutre** [comment]
> I think the problem is underlying that the log files are large in size

That's what I think too. Can you give me the size of the last file ? (if it's 10MB, I will try to fix it, but if it's 2GB, I won't ;) )

> if you load them all in one time, it will not able to display.

Yes I'm actually thinking about a solution for this problem

**Comment by libern** [comment]
Well, I have check my log, they are all around 400MB or some smaller like ~150MB.

I think the solution is that you read files line by line and only read those lines needs to be displayed.

If the next page, or different log file, just reread again, without using javascript to achieve.

**Comment by TheShiftExchange** [comment]
400mb for a log file? That seems exceptionally huge. Most of my sites only run at a few mb... perhaps you are logging too much?

**Comment by libern** [comment]
It might be because my app is huge and there are tons of components. Which will generate same exception repeatedly depends on how many visitors

**Comment by rap2hpoutre** [comment]
400mb is to huge. I don't know how to fix it. It could read file line by line, but just after it has to parse file with regex, send it to view, and render it. So it won't work. Now, I have added a feature in v0.3.0: it does not display files >50mb, but there is a download link in this case. So, no bug but less feature. Sorry :/
