### ISSUE TITLE
feature suggestion

### ISSUE THREAD

**Issue by UnrulyNatives** [rap2hpoutre/laravel-log-viewer#31]
I often get errors in view files. Such as this one:
`storage/framework/views/43b5cdd1d840a31e686df15ac113ab92:45`.

It would be just great to be able to click the filename and see the content - and match the line with `blade` file 
or at least somehow get the filename of the original `blade` file.

Now I am forced to 
- get the cached view file, 
- open it locally
- identify the right blade file
- find the corresponding line in the `blade` file
- fix it
70% of debugging time goes to the procedure of locating the problematic spot.

Great repo, BTW!! 
Thx

**Comment by rap2hpoutre** [comment]
Good point! I will try to do something for this.

**Comment by rap2hpoutre** [comment]
I don't know if we can get blade file name by view file name. I did not found anything about this. And I don't know if it's possible: a view is composed of many blade files. So no solution for your problem right now, sorry.

**Comment by UnrulyNatives** [comment]
I noticed that the names of the view files in `storage` are the same in production and in my local copy. 
We would have to determine if the names are purposefully obfuscated, or are easy to reverse. 

I guess we could find a place where they are rendered and store the corresponding names(source name and the `looks-like-random` name in a DB or text array. 

It is beyond me to do such a thing, but sooner or later I wil certainly get to it.
