### ISSUE TITLE
feature suggestion - button to erase log files

### ISSUE THREAD

**Issue by UnrulyNatives** [rap2hpoutre/laravel-log-viewer#32]
Sometimes i need to clean the content of the most recent LOG file - just to avoid confusion. 
A button doing that would be a great idea

**Comment by rap2hpoutre** [comment]
Deleting log can be dangerous ("oops !"). Thanks to log rotate, i don't need to delete logs in nginx, syslog, laravel, etc.

**Comment by UnrulyNatives** [comment]
you are right. 
How about hiding all logs except the most recent one?

**Comment by rtconner** [comment]
I want this feature. Please don't force your lack of features on me because you think it's dangerous. Just make it a config option.

**Comment by rap2hpoutre** [comment]
@UnrulyNatives @rtconner Ok, I though again about this request, and I decided to quickly add this feature. You can now delete logs, just update to v0.4.0. Hope it will help you :)
