### ISSUE TITLE
Support for changing blade delimiters

### ISSUE THREAD

**Issue by linxgws** [rap2hpoutre/laravel-log-viewer#33]
I change blade's default delimiters in my laravel project, like so:

```
/*-------------------------------------------------------------------------
| Change default Blade delimiters
|------------------------------------------------------------------------*/
Blade::setContentTags('[[', ']]');				// for variables and all things Blade
Blade::setEscapedContentTags('[[#', '#]]');		// for escaped data
```

Which makes Laravel Log viewer not play well, I have to go and edit the views in the source to change all the delimiters.

Any way you can add a feature that detects what the current delimiters are and use those for the log view?

**Comment by rap2hpoutre** [comment]
Ok, so maybe not using blade is a solution, just raw php, I will think about it. You can extends view if you want to use your own blade delimiter, so it can be a solution for now. I'm curious: why did you need to change blade delimiter?

**Comment by linxgws** [comment]
Its common for AngularJS frontends to change the default Laravel delimiters because Angular uses the same {{ }} delimiters by default.

**Comment by rap2hpoutre** [comment]
Ok thanks! Did you know that you have a (cleaner) alternative: 

http://laravel.com/docs/5.1/blade#displaying-data -> Blade & JavaScript Frameworks

**Comment by linxgws** [comment]
Good tip. Still not ideal though, requires extra work for frontend devs to remember the @ symbols everywhere.

A lot cleaner to just change Laravel's to [[ ]] since the vast majority (99%) of expressions for an Angular based project will be using Angular's way over Laravel's.

I did fix this problem on my own by recreating the entire log page and rerouting to it instead of the default one included by laravel-log-viewer.

Just thought it was worth a look to see if there was an easy way to avoid using (or change dynamically) the Laravel braces in case any other Angular devs out there decide to use your package.

**Comment by rap2hpoutre** [comment]
Ok, thank you. I keep this ticket open, feel free to send a PR if you want, I don't know how to fix it right now.

**Comment by rap2hpoutre** [comment]
Anyway, replacing blade delimiters seems to be an outdated and undocumented method (nothing about this in 5.1 docs). It's the way in old posts, but not now (http://ericlbarnes.com/simplest-way-use-laravel-blade-angularjs-together/, https://laracasts.com/discuss/channels/general-discussion/angularjs-and-blade, http://stackoverflow.com/a/28918055/978690, https://www.reddit.com/r/laravel/comments/2d6op8/laravel_angularjs_have_you_all_been_using_them/).

Thanks for contributing, if you found an easy solution you can post it as a pull request, but right now I close this issue
