### ISSUE TITLE
Could we disable auto refresh

### ISSUE THREAD

**Issue by newtonianb** [rap2hpoutre/laravel-log-viewer#35]
This feature is completely freezing up my browser every time when I have alot of data. until this becomes a setting could you give me a pointer as to where to disable it in the code?

**Comment by rap2hpoutre** [comment]
There is no "auto refresh" feature, unless I am mistaken. Can you clarify your request? Is it about a long page load time, because your log are big?

**Comment by newtonianb** [comment]
ah ok, then it must be because I have too many entries sometimes it feels like its refreshing/crashing.
Showing 1 to 10 of 12,152 entries

I feel the pagination is not really working, it seems to load everything?

We use the logs for outputting SQL queries so it gets big really fast and its really slow.

Maybe then disabling pagination would actually make things faster so it doesn't have to process through it all.

**Comment by rap2hpoutre** [comment]
> I feel the pagination is not really working, it seems to load everything?
Yes :/

I will try to fix it in this issue: https://github.com/rap2hpoutre/laravel-log-viewer/issues/43

**Comment by newtonianb** [comment]
Ah that would make sense why it's so slow if it's trying to load everything. Thanks a lot!
