### ISSUE TITLE
Proposal: show emails in html format

### ISSUE THREAD

**Issue by rafaelbeckel** [rap2hpoutre/laravel-log-viewer#38]
It would be very useful to see the rendered html message in log when we are debugging e-mail workflow using "log" driver.

I've managed to do that modifying log.blade.php @line 87 to be like this:

```php
@if(!strpos($log['stack'],'Content-Transfer-Encoding'))
    <div class="stack" id="stack{{{$key}}}" style="display: none; white-space: pre-wrap;">{{{ trim( $log['stack'] ) }}}</div>
@else
    <div class="stack" id="stack{{{$key}}}" style="display: none;">{!! preg_replace('/(Content-Transfer-Encoding[^\n]+)/', '$1<br><br>', $log['stack']) !!}</div>
@endif
```

It basically detects the last mail header and prints the unescaped html message, if the log entry is an e-mail.

It's a dirty hack and needs some cleanup, but worked pretty well for me. ;)

May I submit a PR?

**Comment by rafaelbeckel** [comment]
Before the PR, I think I need to print the subject and headers in a prettier way, and also give the option for the user to see the raw log.

**Comment by rap2hpoutre** [comment]
I think it will maybe open security issue (https://www.owasp.org/index.php/Log_Forging or https://www.owasp.org/index.php/Log_injection) because it's unescaped.

**Comment by rafaelbeckel** [comment]
I see. In my case, the "/logs" route has a middleware that only allows execution in local environment and debug set to true. Anyway, there are safer ways to do that, like allowing only specific sets of html tags and manually rendering them, instead of outputting the entire unescaped text as-is.

**Comment by rap2hpoutre** [comment]
Some people uses laravel-log-viewer in production environment (with middleware that only allows administrator). A user can type a malicious html code in a mail or wathever (without access to log-viewer, just by typing his name or something like that), then, when you open your logs, if the code is unprotected, it will be executed. So the administrator will run the code that the user wrote. Writing unvalidated user input to log files can allow an attacker to forge log entries or inject malicious content into the logs. Hope it's clear, are you Ok with this?

**Comment by rafaelbeckel** [comment]
Well, but who will ever use the "Log" driver in a production environment? In production, all mail go to Mandrill or SMTP or whatever. It never gets logged. Log driver is only meant for development envs.

It's pretty damn useful for fast iteraction of e-mail workflow development: just go to whatever route that dispatches an e-mail job, then go to /logs and click on a URL contained in the e-mail (confirm your account link, for example).

If there's some tiny detail to adjust in the e-mail template, just fix it and go to the route again, then update the logs tab. It's just handy and fast.

In the last message, I commented about cherry-picking and allowing just specific html tags, like <a>, <b> and <table>; and escaping everything else. It wouldn't use the dangerous {!! !!} constructors, but instead prepares the output in an array and show it carefully. Also, most transactional e-mails aren't user-generated.

I'll push a PR when I have some time, taking care of those security issues, then you can evaluate if it's safe enough. ;)

**Comment by rap2hpoutre** [comment]
Ok, I think I understand your needs. You can send a PR or fork the project. Actually, I think this project is  more a log "text" viewer than a log "html" viewer. I'm not sure we will add configuration option (I want to keep this project light), so I'm not sure I will accept the PR. You can try, and we will discuss about it, but maybe you will have to work on your fork.
Thanks again for contributing :)
