### ISSUE TITLE
External layout

### ISSUE THREAD

**Issue by a-komarev** [rap2hpoutre/laravel-log-viewer#39]
It would be great to have config file with ability to use own layout file and integrate it seamlessly in backend application.

**Comment by rap2hpoutre** [comment]
You can customize views if you want to have your own layout: https://github.com/rap2hpoutre/laravel-log-viewer/issues/9
I'm not sure I want to add config file because I want to keep this package as simple as possible.

**Comment by a-komarev** [comment]
Oh, thank you!

It's just enough to create folder `/resources/views/vendor/laravel-log-viewer` and put there a file `log.blade.php`.

It works.

**Comment by judgej** [comment]
I personally think that just splitting the view into two - a layout view and a content view - would be a great update to this package. That way people can choose to continue to use the core view, unchanged (getting updates as needed) and still use their own wrapper/layout view.

**Comment by rap2hpoutre** [comment]
Yes that's a good idea! Could you open a new ticket (or a Pull Request if you want) for this need? Anyway, thanks a lot, I think it would improve this log viewer!
