### ISSUE TITLE
add possibility of modifing the view

### ISSUE THREAD

**Issue by 7henry767** [rap2hpoutre/laravel-log-viewer#41]
How is it possible / is it even possible to modify the look (e.g include the logviewer in the own website design)?

**Comment by rap2hpoutre** [comment]
Yes, it's possible! You can have a look at this two posts: https://github.com/rap2hpoutre/laravel-log-viewer/issues/39 & https://github.com/rap2hpoutre/laravel-log-viewer/issues/9

**Comment by 7henry767** [comment]
Thanks
