### ISSUE TITLE
Request: Reduce white space in the tables

### ISSUE THREAD

**Issue by judgej** [rap2hpoutre/laravel-log-viewer#42]
This log viewer will be viewing some massive files, which thousands of entries. The table that is rendered has thousands of rows, and many more table cells.

All this is padded out with white space from the view, which can add megabytes to a page, and contribute to the browser crashing. Can this white space between elements, and around data in table cells, be stripped out? I'm not sure how to suggest this is done, while preserving the readability of the source view, but there must be a way.

**Comment by rap2hpoutre** [comment]
Ok, thanks, I've just try something (removing extra space and trying to preserve readability). You can update to v0.4.2.  About big log file, there are several problem with it (https://github.com/rap2hpoutre/laravel-log-viewer/issues/35, https://github.com/rap2hpoutre/laravel-log-viewer/issues/29, https://github.com/rap2hpoutre/laravel-log-viewer/issues/10, etc.) and my only answer right now is... try to make it smaller! (do you use daily log rotate?)

**Comment by judgej** [comment]
Daily log rotates are on, yes. I had an error (with a 55-line stack dump) every minute on a scheduled job over the weekend, so you can imagine how quickly that built up, even with daily logs.
