### ISSUE TITLE
Request: AJAX viewing

### ISSUE THREAD

**Issue by judgej** [rap2hpoutre/laravel-log-viewer#43]
Instead of loading an entire logfile in one go, can we use AJAX to fetch just the rows that are needed? Datatable is really good at this, and it is surprisingly easy to do with a package to handle the server side, such as https://github.com/yajra/laravel-datatables

**Comment by rap2hpoutre** [comment]
Ok thank you! I'll have a look at this as soon as possible. I think there are two problem in this log viewer on big log files: loading in server side (I don't know how to improve it right now) and loading in client side (your suggestion could improve it).

**Comment by judgej** [comment]
There are suggestions on how to efficiently count the lines in a file here:

http://stackoverflow.com/questions/2162497/efficiently-counting-the-number-of-lines-of-a-text-file-200mb

Watch out for line ending characters though. This can be expanded to extract N lines starting at line L.

Querying would be a little more work - starting at line L you need to extract N lines that match the query string, or you reach end of file. Probably not too difficult though.

So given the start line, the number of lines, and any query string (all passed in as GET parameters through a Datatable, the lines of the log file are put into a simple JSON response and that's it. I think it would be relatively straight-forward without needing to us any third-party packages.

Using Datatables like this, all your initial page would deliver is the table headers and the JS to map the returned data onto the table columns, then Datatables does the rest.

I'll see what kind of demo I can knock together. I'll check the other forks first though, as there are a few of them, and someone may already have done this.

**Comment by rap2hpoutre** [comment]
It's a good idea, thank you! Would you like to work on it and send a PR? ;) I could too, but I don't know when.

**Comment by judgej** [comment]
Been looking around for solutions to this, but not come up with anything yet. The problem with taking sections, i.e. pages, from a log file, is indexing; the logfiles are not indexed.

Each logfile has has many entries, each being a variable number of lines but starting with a matching pattern (that may vary, depending on laravel settings). The order of the logged messages is backwards, so the last entry should be top of the first page. So you cannot could lines in the file to find a particular error log entry, unless it has been previously indexed. The index may be the key in the end - a list of timestamps, and byte-count offset at which those lines start. If each had a timestamp, that would be something else that could be range-searched on.

A text search of everything in the file would involve a full-table scan, so there is no much we can do about that, but it's the reverse order that is always going to be the problem - you can't just start at the end and work backwards.

So I'm looking for tools that will index a text file, given that some entries in that file will cover multiple lines.

**Comment by yajra** [comment]
Guys, I just implemented the server-side processing of datatables for this awesome package on my own controller. And instead of toggling, I used modal box to display the full error stack message. If you like, I can create a PR for it. 

@rap2hpoutre thanks for this great package. 

Below is the snippet I used:
***Controller***
```php
public function logs(Request $request, Datatables $datatables)
    {
        if ($request->input('l')) {
            LaravelLogViewer::setFile(base64_decode($request->input('l')));
        }

        if ($request->input('dl')) {
            return response()->download(LaravelLogViewer::pathToLogFile(base64_decode($request->input('dl'))));
        } elseif ($request->has('del')) {
            File::delete(LaravelLogViewer::pathToLogFile(base64_decode($request->input('del'))));

            return redirect()->to($request->url());
        }

        $logs = LaravelLogViewer::all();

        if ($request->wantsJson()) {
            return $datatables->collection(collect($logs))
                              ->editColumn('stack', '{!! nl2br($stack) !!}')
                              ->editColumn('level', function ($log) {
                                  $content = $this->html->tag('span', '', [
                                      'class' => "glyphicon glyphicon-{$log['level_img']}-sign",
                                  ]);

                                  $content .= '&nbsp;' . $log['level'];

                                  return $this->html->tag('span', $content, ['class' => "text-{$log['level_class']}"]);
                              })
                              ->addColumn('content', function ($log) {
                                  $html = '';
                                  if ($log['stack']) {
                                      $html = '<a class="pull-right expand btn btn-default btn-xs"><span class="glyphicon glyphicon-search"></span></a>';
                                  }

                                  $html .= $log['text'];

                                  if (isset($log['in_file'])) {
                                      $html .= '<br>' . $log['in_file'];
                                  }

                                  return $html;
                              })
                              ->make(true);
        }

        return view('administrator.utilities.log', [
            'logs'         => $logs,
            'files'        => LaravelLogViewer::getFiles(true),
            'current_file' => LaravelLogViewer::getFileName(),
        ]);
    }
```

JS Script:
```js
    $(document).ready(function () {
        var oTable = $('#table-log').DataTable({
            "order": [1, 'desc'],
            "serverSide": true,
            "processing": true,
            "ajax": "",
            "stateSave": true,
            "columns": [
                {data: "level"},
                {data: "date"},
                {data: "content"}
            ]
        }).on('click', '.expand', function () {
            var tr = $(this).parents(tr);
            var data = oTable.row(tr).data();
            $('#stack-text').html(data.text);
            if (! data.in_file) {
                $('#stack-file').hide();
            } else {
                $('#stack-file').show();
                $('#stack-file').html(data.in_file);
            }
            $('#stack-details').html(data.stack);
            $('#stack-modal').modal('show');
        });

        $('#delete-log').click(function () {
            return confirm('Are you sure?');
        });
    });
```
**Modal Box**
```php
<div class="modal fade" id="stack-modal">
    	<div class="modal-dialog modal-lg">
    		<div class="modal-content">
    			<div class="modal-header">
    				<button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
    				<h4 class="modal-title" id="stack-text"></h4>
    			</div>
    			<div class="modal-body">
    				<div id="stack-file" class="lead"></div>
    				<div id="stack-details"></div>
    			</div>
    			<div class="modal-footer">
    				<button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
    			</div>
    		</div>
    	</div>
    </div>
```

**Comment by judgej** [comment]
I'm still thinking about how the files can be read without loading the whole thing into memory. I think it *has to* include pre-processing to index the file to achieve this. Given a two-way index of file line numbers to error record numbers, it is possible to seek directory to record number in order to read however many records are needed, without loading the whole file into memory.

Paging through a search result is a little more tricky, but would be helped if the start record of each page were scanned for and cached when a search is first performed.

I realise log files should generally not be too big anyway, but when things go wrong they can grow in size quickly, and that happens to be when you need to be able to view them the most.

**Comment by yajra** [comment]
Good point at trying to pre-process the log file and I don't have any idea how to do it ^_^. 

But for displaying purposes ATM, the performance significantly improved when I converted this package to server-side pagination and search.

**Comment by judgej** [comment]
So could your excellent [laravel datatables](https://github.com/yajra/laravel-datatables) package be used here for rendering? Or does your package focus more on linking the tables to eloquent?

**Comment by yajra** [comment]
@judgej Yes, you can use the snippet above to implement your own log viewer like what I did. `$logs = LaravelLogViewer::all();` returns an array and the trick is to just convert it to collection using `collect()` helper method.

```php
$logs = LaravelLogViewer::all();

if ($request->wantsJson()) {
    return $datatables->collection(collect($logs))->make(true);
}
```

**Comment by judgej** [comment]
monolog can [write direct to sqlite](https://github.com/Seldaek/monolog/blob/master/doc/04-extending.md) which is one way to get access to the logs through eloquent. It seems safer writing logs to raw text, so maybe the logfiles can be parsed and new log entries pushed into an sqlite database - that's all the indexing, queries, searches etc, sorted.

I'll just leave that idea hanging there, and come back to it later :-)

**Comment by rap2hpoutre** [comment]
This issue is super old (3 years) and I only maintain this package without adding new features. I close this issue. Feel free to ask for reopen.

**Comment by souravmack** [comment]
can you update LaravelLogViewer.php
$file = file_get_contents($this->file,false,null,0, 2097152);

2097152 is the size of file we want to access, which can be defined in config.app file.
