### ISSUE TITLE
Empty logs rather than delete

### ISSUE THREAD

**Issue by TechKat** [rap2hpoutre/laravel-log-viewer#45]
It's a great feature to delete logs you no longer need, but for log files that will be recreated (Such as lumen.log or laravel.log), wouldn't it be best to just empty it?

**Comment by rap2hpoutre** [comment]
Ok thanks. If you use log rotate (http://laravel.com/docs/5.1/errors), this will be probably useless: you don't want to keep your old empty file I think. Anyway, why recreate a file could be a problem?
