### ISSUE TITLE
Request: Remove lines

### ISSUE THREAD

**Issue by ffsantos92** [rap2hpoutre/laravel-log-viewer#48]
It would be useful a new feature for removing log lines.

**Comment by rap2hpoutre** [comment]
Thanks for your suggestion!
Anyway, should we remove lines from a log? I think a log should not be modified: think about access log or syslog or even error log. Could you explain why you need this?

**Comment by ffsantos92** [comment]
In situations when log is accessed by more than one person, this could be a nice feature to mark errors as solved.

**Comment by rap2hpoutre** [comment]
Ok, I understand. This package is just a small log viewer, maybe you could use a bug tracking system for this need (we are using bugsnag in my team, we just use this log viewer to dig into/analyze logs). I want to keep this log viewer light and simple. Maybe [ARCANEDEV's LogViewer](https://github.com/ARCANEDEV/LogViewer) has this feature, I did not tried it.

**Comment by rtconner** [comment]
Yeah this request is more than I'd expect from a log viewer. Kind of opens up a whole can of worms of crazy features that most people would never use.

**Comment by ffsantos92** [comment]
I agree with @rtconner. I'll try GetSentry or Bugsnag :smiley: 

ping > @pedrogrou
