### ISSUE TITLE
Laravel 5 Blade Tag

### ISSUE THREAD

**Issue by thangngoc89** [rap2hpoutre/laravel-log-viewer#5]
On Laravel 5, Blade Tag `{{ .. }}` was changed to `{!! .. !!}`.
https://github.com/rap2hpoutre/laravel-log-viewer/blob/master/src/views/log.blade.php#L82

**Comment by rap2hpoutre** [comment]
Ok thanks ! Fixed in v0.1.10 :)
(you only have to run composer update)
