### ISSUE TITLE
ServiceProvider not found

### ISSUE THREAD

**Issue by IgorKostine** [rap2hpoutre/laravel-log-viewer#53]
Hi !

I use laravel 4.2
I have this error message when i want going on the log page
Class 'Rap2hpoutre\LaravelLogViewer\LaravelLogViewerServiceProvider::class' not found 

thx !

**Comment by rap2hpoutre** [comment]
Ok what's your php version?

**Comment by IgorKostine** [comment]
PHP 5.4.45

**Comment by pawanshetty** [comment]
Even I am getting the same error ,

**Comment by rap2hpoutre** [comment]
The `class` keyword was added in PHP 5.5, so it will not work with your version. You should replace this (in your `config/app.php` in `providers` section):
```
Rap2hpoutre\LaravelLogViewer\LaravelLogViewerServiceProvider::class,
```
by this:
```
'\Rap2hpoutre\LaravelLogViewer\LaravelLogViewerServiceProvider',
```
And it will work. Source: 
http://php.net/manual/en/language.oop5.basic.php#language.oop5.basic.class.class

**Comment by rap2hpoutre** [comment]
(or you could update your php version to 5.5, 5.6 or 5.7)

**Comment by IgorKostine** [comment]
Thank you for your answer !

**Comment by AbdullahJisat** [comment]
my log viewer couldn't find. I follow your instruct

**Comment by 7592024404** [comment]
In ProviderRepository.php line 208:

  Class "Rap2hpoutre\LaravelLogViewer\LaravelLogViewerServiceProvider" not found
