### ISSUE TITLE
request() is a undefined function

### ISSUE THREAD

**Issue by AdrianHL** [rap2hpoutre/laravel-log-viewer#54]
The controller class has two uses of request as a function so the controller is failing in Laravel 4. The change was introduced in https://github.com/rap2hpoutre/laravel-log-viewer/commit/02c6ddd38e417ea5c96042f9195264201ed966ae

**Comment by CharlesHenry** [comment]
This also seems to break Laravel v5.0 since laravel-log-viewer v0.5.0

**Comment by rap2hpoutre** [comment]
Resolved. Available in v0.5.3 (thanks to @CharlesHenry)
