### ISSUE TITLE
error

### ISSUE THREAD

**Issue by sciracioglu** [rap2hpoutre/laravel-log-viewer#57]
hi,
i get this error how can i fix this?
InvalidArgumentException in FileViewFinder.php line 112: No hint path defined for [laravel-log-viewer].

thanks

**Comment by rap2hpoutre** [comment]
There was a similar issue here: https://github.com/rap2hpoutre/laravel-log-viewer/issues/17

> Did you add 'Rap2hpoutre\LaravelLogViewer\LaravelLogViewerServiceProvider' in config/app.php file (in providers section, line 147 on a fresh install) ?

**Comment by rap2hpoutre** [comment]
@sciracioglu Does it solve your problem?
