### ISSUE TITLE
Lumen compatibility

### ISSUE THREAD

**Issue by moh-abk** [rap2hpoutre/laravel-log-viewer#60]
I get `Class App\Http\Controllers\\Rap2hpoutre\LaravelLogViewer\LogViewerController does not exist` when using this with Lumen

**Comment by rap2hpoutre** [comment]
It is not compatible with Lumen right now (I have never tried it with Lumen). I will take a look at this problem asap. Anyway, feel free to send a PR if you find a solution.

**Comment by rap2hpoutre** [comment]
Could you please add the backtrace? It's a problem about fully qualified name but I don't know where to fix it in Lumen's framework code.

**Comment by rap2hpoutre** [comment]
Fixed: https://github.com/rap2hpoutre/laravel-log-viewer/pull/66
