### ISSUE TITLE
Permission Denied

### ISSUE THREAD

**Issue by morfin** [rap2hpoutre/laravel-log-viewer#64]
Getting this:
ErrorException in Filesystem.php line 109:
file_put_contents(/8414948cc128b33a8c074d83101ba69d62cc89a5.php): failed to open stream: Permission denied

/storage/logs/laravel.log has 777 permissions. 

Any idea?

Thanks.

**Comment by morfin** [comment]
Found solution:
https://laracasts.com/discuss/channels/general-discussion/errorexception-in-filesystemphp-line-75

**Comment by rap2hpoutre** [comment]
Ok thank you :)
