### ISSUE TITLE
[Insight] Class should be unique per PHP file - in src/controllers/LogViewerController.php, line 0

### ISSUE THREAD

**Issue by rap2hpoutre** [rap2hpoutre/laravel-log-viewer#67]
**[in src/controllers/LogViewerController.php](https://github.com/rap2hpoutre/laravel-log-viewer/blob/7f34b6c4bd02917ec2d2e208e76e04517fea4f45/src/controllers/LogViewerController.php#L0)**

> This file contains 3 classes. Keeping only one class per file is a standard in the PHP community, since it promotes interoperability and maintainability.
- BaseController (defined at **[line 5]()**)
- BaseController (defined at **[line 7]()**)
- LogViewerController (defined at **[line 16]()**)

---

_Posted from [SensioLabsInsight](https://insight.sensiolabs.com/projects/2974f007-ff84-41a7-8954-7cda41ca5f84/analyses/52)_

**Comment by rap2hpoutre** [comment]
ping @abarreir

**Comment by greabock** [comment]
Lol... bots are so bots. It's is not a bug but just a trick

**Comment by rap2hpoutre** [comment]
You are right, but I'm so sad now: this package was 100/100, and now only 37/100. But who cares ? ;)

**Comment by rap2hpoutre** [comment]
I give up :)
