### ISSUE TITLE
InvalidArgumentException in FileViewFinder.php line 112: No hint path defined for [laravel-log-viewer].

### ISSUE THREAD

**Issue by jdanielzr** [rap2hpoutre/laravel-log-viewer#68]
I have that mistake, and try several ways and nothing

**Comment by rap2hpoutre** [comment]
You could have a look to this issue https://github.com/rap2hpoutre/laravel-log-viewer/issues/57

**Comment by rap2hpoutre** [comment]
Did it solve your problem?

**Comment by schonhose** [comment]
This is generally caused by a caching error.

`php artisan config:cache` solves this problem.

**Comment by rap2hpoutre** [comment]
@schonhose Thanks!

**Comment by schonhose** [comment]
yw, great log viewer! Works like a charm.

**Comment by gocanto** [comment]
This is how it worked for me ```php artisan clear-compiled```.

Just in case somebody else ran into the same issue. 

Thanks!

**Comment by ranvir-floweraura** [comment]
Thanks @gocanto that worked for me.
`php artisan clear-compiled`

**Comment by ahmeraq** [comment]
not working in Lumen, In fact clear, vendor and config command doesn;t come by detault in lumen.
