### ISSUE TITLE
Request: Add support for seeing context

### ISSUE THREAD

**Issue by mallardduck** [rap2hpoutre/laravel-log-viewer#69]
Some times I find it useful to set a custom context when logging and it'd be awesome to see this shown in the table.

When I do this it allows me to see where particular logging is coming form in my apps, I know it's not something that everyone may think is essential but to me this would be a great help. I believe it should be pretty darn easy to get setup too.

I think I'll submit a patch for this later tonight if I'm able to get it working.

**Comment by mallardduck** [comment]
I've submitted #70 that addresses this request.

**Comment by rap2hpoutre** [comment]
OK thank you! :+1:
