### ISSUE TITLE
[Proposal] Show additional information in sidebar?

### ISSUE THREAD

**Issue by seblavoie** [rap2hpoutre/laravel-log-viewer#73]
Hi, I have just discovered this package and love it. I was wondering what you'd think about adding additional information on rollover on links in the sidebar? I think the file size and the number of entries would be two valuable informations to have without having to click and load the file.

**Comment by rap2hpoutre** [comment]
Thanks! I'm happy you like it! 

That's a good idea, not sure if it will be useful for everyone though. I'm curious: why do you want to know the file size?

**Comment by seblavoie** [comment]
Well sometimes when things go sour, apps can start logging errors on a loop and make the logs gigantic. Which can result in server memory saturation. I think this would be a way to easily locate log file that has become too big.

**Comment by rap2hpoutre** [comment]
Ok!

**Comment by rap2hpoutre** [comment]
Too old, I close sorry...
