### ISSUE TITLE
use custom view

### ISSUE THREAD

**Issue by doghap** [rap2hpoutre/laravel-log-viewer#76]
how can i use custom view ?  Because these cdns that used in your view is so slow in my country (china), and i want to change direction and font-family to make my logs looks nicer (arabic letters).

**Comment by ImPerat00r** [comment]
I think you can rewrite LogViewerController, then use your custom view instead.

```
return View::make('laravel-log-viewer::log', [
            'logs' => $logs,
            'files' => LaravelLogViewer::getFiles(true),
            'current_file' => LaravelLogViewer::getFileName()
        ]);
```
