### ISSUE TITLE
Reminder : Please mention to clear cache in Readme.

### ISSUE THREAD

**Issue by cjmling** [rap2hpoutre/laravel-log-viewer#79]
As it is already mentioned here in https://github.com/rap2hpoutre/laravel-log-viewer/issues/68#issuecomment-251204610  to clear the cache. 

Damn I spend at least an hour to find the cause of that 'hint path' error.   Will be really helpful for future who face same problems like me.

Thanks , Great Log Viewer

**Comment by rap2hpoutre** [comment]
Thank you, you are right! I will add a "FAQ" section mentioning this and some other frequent questions asap. Thanks 👍

**Comment by rap2hpoutre** [comment]
Fixed: https://github.com/rap2hpoutre/laravel-log-viewer/commit/75d0261b817d13e354df6c652a1ce0207ad88b89

Thank you again!
