### ISSUE TITLE
Can't find the controller class. Maybe namespace error?

### ISSUE THREAD

**Issue by fasthold** [rap2hpoutre/laravel-log-viewer#8]
Hi,

When I add the code `Route::get('logs', 'Rap2hpoutre\LaravelLogViewer\LogViewerController@index');` to routes.php, and then visit `http://myapp/logs` , it shows 

`
Class App\Http\Controllers\Rap2hpoutre\LaravelLogViewer\LogViewerController does not exist
`

How can I fix it? Thanks!

**Comment by rap2hpoutre** [comment]
Ok you can try something else:

Add this at the end `map` function in `app/Providers/RouteServiceProvider.php`
```
$router->group(['namespace' => 'Rap2hpoutre\LaravelLogViewer'], function($router) {
    Route::get('logs', 'LogViewerController@index');
});
```
And remove the line you added in `routes.php`.

It should work. I will update README instructions asap.

**Comment by fasthold** [comment]
Yeah, it works!
But the working code is:
```php
$router->group(['namespace' => 'Rap2hpoutre\LaravelLogViewer'], function($router) {
    $router->get('logs', 'LogViewerController@index');
});
```
Thanks a lot!

**Comment by rap2hpoutre** [comment]
Great (thanks for your working code :+1: )

**Comment by younes0** [comment]
this at the end map function ? I'm not understanding

Besides I can't think of a single app not requiring this

**Comment by younes0** [comment]
nice startup btw

**Comment by younes0** [comment]
EDIT

**Comment by rap2hpoutre** [comment]
Thanks!
You don't need to do this trick anymore in laravel >= 5.1. Documentation is already updated, just use:
`Route::get('logs', '\Rap2hpoutre\LaravelLogViewer\LogViewerController@index');`
(don't forget the first backslash)
