### ISSUE TITLE
Instruction not working for Lumen 5.3

### ISSUE THREAD

**Issue by chmdznr** [rap2hpoutre/laravel-log-viewer#82]
Got this error after following the installation instruction for Lumen:
`Class App\Http\Controllers\Rap2hpoutre\LaravelLogViewer\LogViewerController does not exist`

FYI, the route's settings file in Lumen 5.3 is on: `routes/web.php`

**Comment by rap2hpoutre** [comment]
Ok, sorry! Replace:
```
$app->register(Rap2hpoutre\LaravelLogViewer\LaravelLogViewerServiceProvider::class);
```
By:
```
$app->register(\Rap2hpoutre\LaravelLogViewer\LaravelLogViewerServiceProvider::class);
```
In other words, add a leading backslash. Thank you, I will edit the readme soon!

**Comment by chmdznr** [comment]
Still got the same error even after adding a backslash. The whole route:
```
$app->get('/', function () use ($app) {
    return $app->version();
});

$app->get('/what', function () use ($app) {
    return "what the heck....";
});

$app->group(['namespace' => '\Rap2hpoutre\LaravelLogViewer'], function() use ($app) {
    $app->get('logs', 'LogViewerController@index');
});
```

**Comment by rap2hpoutre** [comment]
The backslash must be added in `bootstrap/app.php`. Not in routes. Is it what you have done?

**Comment by chmdznr** [comment]
Yes, it is. This is my `bootstrap/app.php` (just the service provider regist. part):
```
$app->register(App\Providers\AppServiceProvider::class);
// $app->register(App\Providers\AuthServiceProvider::class);
// $app->register(App\Providers\EventServiceProvider::class);
$app->register(\Rap2hpoutre\LaravelLogViewer\LaravelLogViewerServiceProvider::class);
```

**Comment by rap2hpoutre** [comment]
Oops. Ok I did not misread the error message. Sorry about that. I have to understand and fix the bug.

**Comment by rap2hpoutre** [comment]
It seems it's a lumen issue. Just posted a PR here: https://github.com/laravel/lumen-framework/pull/541

**Comment by chmdznr** [comment]
Wow!
Your patch on lumen is really working (while waiting for the merge, I edited the problematic file and test it by myself)!
So, it's lumen problem.

**Comment by rap2hpoutre** [comment]
Fixed (PR merged): https://github.com/laravel/lumen-framework/pull/541

Thanks for your contribution!

**Comment by ToujouAya** [comment]
@rap2hpoutre 
I got same problem like this
I have config like this in bootstrap\app.php file
`$app->register(\Rap2hpoutre\LaravelLogViewer\LaravelLogViewerServiceProvider::class);`
and in routes.php file

`$app->group(['namespace' => '\Rap2hpoutre\LaravelLogViewer'], function() use ($app) {
    $app->get('logs', 'LogViewerController@index');
});`

How to fix it? 
Thanks

**Comment by rap2hpoutre** [comment]
@ToujouAya It was a problem with Lumen. I fixed it here: https://github.com/laravel/lumen-framework/pull/541

Now we just have to wait for Taylor Otwell (creator of Laravel & Lumen) to release a version with this fix. I may be released in a few days.

3 solutions for you:
 - Wait for the new version and update lumen
 - Use my fork of Lumen (which includes the fix): https://github.com/rap2hpoutre/lumen-framework
 - Edit the file just like @chmdznr

**Comment by ToujouAya** [comment]
@rap2hpoutre  
I understood, thanks

**Comment by gopal-g** [comment]
is this fix released yet ? I am on Lumen 5.3.3 and still stuck with this bug :(

**Comment by oknixus** [comment]
Sorry, I encountered the same problem. But my lumen framework is 5.5; 
How can I fix it ?
Thanks a lot.

**Comment by rap2hpoutre** [comment]
@oknixus Hi! What's in your `bootstrap/app.php`?

**Comment by oknixus** [comment]
@rap2hpoutre Thanks for your attentions. I tried two ways:
`$app->register(\Rap2hpoutre\LaravelLogViewer\LaravelLogViewerServiceProvider::class);`
and 
`$app->register(Rap2hpoutre\LaravelLogViewer\LaravelLogViewerServiceProvider::class);`

but the problem  always exists;
