### ISSUE TITLE
Lumen install not working

### ISSUE THREAD

**Issue by bret-2600** [rap2hpoutre/laravel-log-viewer#83]
Hello,

Thanks for writing such a great tool.  I'm trying to install it on Lumen and I'm running into issues.  When I run ..

`composer require rap2hpoutre/laravel-log-viewer`

.. a rap2hpoutre folder is added to my vendor folder.  And attempting to access the controller throws an error:

`ReflectionException in Container.php line 749: Class App\Http\Controllers\Rap2hpoutre\LaravelLogViewer\LogViewerController does not exist`

Any help would be much appreciated.

**Comment by rap2hpoutre** [comment]
Thank you for your contribution!
You could try one of these solutions: https://github.com/rap2hpoutre/laravel-log-viewer/issues/82#issuecomment-271247972

It seems the fix has been included in Lumen 5.4, maybe you could just upgrade.

**Comment by bret-2600** [comment]
Upgrading worked!  Thanks a ton!

**Comment by rap2hpoutre** [comment]
You're welcome!
