### ISSUE TITLE
[idea] Clickable row

### ISSUE THREAD

**Issue by ricardocino** [rap2hpoutre/laravel-log-viewer#85]
When looking at errors I think it would be easier to make the complete row or at least the error itself clickable instead of just the magnifier glass on the right.
Reason is because I'm too lazy to move the mouse to the right every time, do others agree with this?

**Comment by ahuggins** [comment]
This PR will make the whole row clickable: https://github.com/rap2hpoutre/laravel-log-viewer/pull/91

**Comment by rap2hpoutre** [comment]
Thanks!
