### ISSUE TITLE
Make it work for Queue Worker logs

### ISSUE THREAD

**Issue by rap2hpoutre** [rap2hpoutre/laravel-log-viewer#86]
Queue worker logs look like this:

```
[2017-03-27 14:00:03] Processed: App\Jobs\ProcessInvitation
[2017-03-27 14:02:21] Processed: App\Jobs\ProcessSomethingElse
```

It is not parsed by the log viewer. We should handle this case, because actually, it just displays:

> No data available in table

(weird)

**Comment by ryanvade** [comment]
I'm seeing the same issue. The log is being generated by jobs run via supervisor. Perhaps it is a file permission issue.

**Comment by rap2hpoutre** [comment]
@ryanvade It's not about permission, it's the regex I use to parse the logs. I need to rewrite this regex to make it work with this kind of logs too.

**Comment by kevmt** [comment]
If possible, if the regex fails just display line-by-line instead.

**Comment by rap2hpoutre** [comment]
Fixed thanks to @ricardocino
