### ISSUE TITLE
Exception: No such log file 

### ISSUE THREAD

**Issue by seanlai** [rap2hpoutre/laravel-log-viewer#92]
Anybody ran into this issue? Clicking on any log file crash with this error:

Exception: No such log file 
in /releases/20170526182153/vendor/rap2hpoutre/laravel-log-viewer/src/Rap2hpoutre/LaravelLogViewer/LaravelLogViewer.php:89
Stack trace:
#0 /releases/20170526182153/vendor/rap2hpoutre/laravel-log-viewer/src/Rap2hpoutre/LaravelLogViewer/LaravelLogViewer.php(67): Rap2hpoutre\LaravelLogViewer\LaravelLogViewer::pathToLogFile('/...')
#1 /releases/20170526182153/vendor/rap2hpoutre/laravel-log-viewer/src/controllers/LogViewerController.php(23): Rap2hpoutre\LaravelLogViewer\LaravelLogViewer::setFile('laravel-2017-05...')
#2 [internal function]: Rap2hpoutre\LaravelLogViewer\LogViewerController->index()

**Comment by rap2hpoutre** [comment]
Ok, sorry! I think it's because of a recent untested change. I just tried to "fix" it (rollback). Could you update (`composer update`) then retry?

**Comment by seanlai** [comment]
thanks, the error went away with v0.10.2
