### ISSUE TITLE
lumen 5.1 Whoops, looks like something went wrong.

### ISSUE THREAD

**Issue by hulkwan** [rap2hpoutre/laravel-log-viewer#93]
after install in lumen 5.1 , everything is ok.
but when i visit http://localhost/logs.

Whoops, looks like something went wrong. 

and i checked the LogViewerController.php . error was happend in 

return app('view')->make('laravel-log-viewer::log', [
            'logs' => LaravelLogViewer::all(),
            'files' => LaravelLogViewer::getFiles(true),
            'current_file' => LaravelLogViewer::getFileName()
        ]);

**Comment by ricardocino** [comment]
As you closed this yourself, would you also want to explain what you did to fix the issue for others who might experience the same? :)
