### ISSUE TITLE
Logs archive GZ 

### ISSUE THREAD

**Issue by DarkCobalt** [rap2hpoutre/laravel-log-viewer#94]
Laravel 5.4 create archive form file logs and he would use a function, letting it unpack it with such a file.
![pastedgraphic-6](https://user-images.githubusercontent.com/5318698/27029494-e88cadd2-4f68-11e7-97ae-1ff406c7b882.png)

**Comment by rap2hpoutre** [comment]
Ok, thanks for contributing! I'm not sure to understand what you wrote. Anyway maybe I should not display `.gz` files.

**Comment by rap2hpoutre** [comment]
Fixed via https://github.com/rap2hpoutre/laravel-log-viewer/pull/96
