### ISSUE TITLE
Show file compiled from storage/framework/views

### ISSUE THREAD

**Issue by DarkCobalt** [rap2hpoutre/laravel-log-viewer#99]
Hi,

It would be cool if you could click on the link in the error list and be able to view the compiled in which the error occurred.

exception 'ErrorException' with message 'Trying to get property of non-object' 
in storage/framework/views/34773a82a02386311564fb509593ce3a:101

**Comment by rap2hpoutre** [comment]
Thanks for contributing! Would you like to submit a PR for this?

**Comment by rap2hpoutre** [comment]
Ping

**Comment by DarkCobalt** [comment]
Ah sorry I have too much case on head, but now i have free time then i will create PR for this :)

**Comment by rap2hpoutre** [comment]
Closed for lack of activity.
